apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator-deployment
  namespace: default
  labels:
    app: password-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: password-generator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: password-generator
    spec:
      containers:
      - name: password-generator
        image: kishorgec/password-generator
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1
            memory: 5120Mi
          requests:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/healthcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/healthcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: ClusterIP
  selector:
    app: password-generator
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: healthcheck
      protocol: TCP
      port: 8080
      targetPort: 8080

