apiVersion: v1
kind: Service
metadata:
  name: password-generator-service
spec:
  type: ClusterIP
  selector:
    app: password-generator
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: healthcheck
      protocol: TCP
      port: 8080
      targetPort: 8080
